### ISSUE TITLE
Dropbox file

### ISSUE THREAD

**Issue by VonKavalier** [subdavis/CKPX#13]
I'm getting that message when trying to connect to Dropbox : 

> This app has reached its user limit. Contact the app developer and ask them to use the Dropbox API App Console to increase their app's user limit.

Is it coming soon ? Will continue using original CKP app until then.

I do love your initiative of continuing that project :)

**Comment by subdavis** [comment]
Thanks for opening this issue.  I'll take a look tonight - it's probably just a setting I need to change.

**Comment by subdavis** [comment]
@VonKavalier please retest this, I believe it is resolved.

**Comment by VonKavalier** [comment]
Yep ! Working perfectly, thanks ! 👍
