### ISSUE TITLE
What key file was used should be remembered between logins

### ISSUE THREAD

**Issue by flaklypa** [subdavis/CKPX#14]
The key file needs to be selected each time you login. The extension should remember which key file was used, as the original extension does.

**Comment by subdavis** [comment]
I completely agree.  Thanks for opening this issue.

**Comment by subdavis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CKPX issue #14](https://trello.com/c/L5U9IG3l/5-ckpx-issue-14)

**Comment by subdavis** [comment]
@flaklypa Thanks for your bug report.   This issue has been resolved in #17

**Comment by subdavis** [comment]
Actually closed in #22
