### ISSUE TITLE
Version: 2017.10.10 breaks unlocking GDrive kdbx

### ISSUE THREAD

**Issue by shikhanshu** [subdavis/CKPX#21]
Everything was fine until yesterday. Today, it says "Error InvalidKey: invalid key" upon Unlocking. Nothing has changed from my side.

Tried de-authorizing and re-authorizing. Did not help.

**Comment by shikhanshu** [comment]
Well, uninstalled the extension and re-installed, thereby forcing it to ask for the master password again, and it works now.

1. It would be good if there were a way to tell the extension to forget master password and ask again for it (I was not able to find this option)
2. Not sure why the 2017.10.10 update did not work with already 'forever remembered' master password.

**Comment by subdavis** [comment]
@shikhanshu  Thanks for opening this issue.  I discovered it myself this morning, and will address it asap.

I think it's serious enough to revert for now, until I have a chance to fully address every bug.
The reverted version will be available in the play store within the hour.

**Comment by shikhanshu** [comment]
But I was already able to get the new version working by uninstalling/reinstalling and re-entering master password. I can stick to the new version and report any more bugs that may crop up.

**Comment by subdavis** [comment]
There were other issues in addition to yours.  What was your password remember period?

**Comment by shikhanshu** [comment]
"Forever". Meanwhile, the extension suddenly broke again! It again says invalid key.
I will revert back to the working version once you release it.

**Comment by subdavis** [comment]
The working version is released, and should be available within 20 min

**Comment by shikhanshu** [comment]
2017.10.11 is what I have now and it seems to work wonderfully. No issues. Thank you Sir!
