### ISSUE TITLE
Not able to authenticate Google drive

### ISSUE THREAD

**Issue by gynet** [subdavis/CKPX#39]
It shows "CKPX needs to view the files in your Google Drive in order to continue. Please press "Accept" on the dialog."  but nothing shows up

**Comment by gynet** [comment]
No issue with CKP

**Comment by subdavis** [comment]
@gynet thanks for this report.  On the settings page where you see this message, could you right click -> inspect, go to the "console" tab and paste in any output you see?

**Comment by gynet** [comment]
Never mind, it works now. It may because the pop window got minimized.

**Comment by subdavis** [comment]
Great, thanks!  I'm going to close this issue, but feel free to open it back up if the problem comes back.
